[tool.poetry]
name = "setup-task"
version = "0.0.0"
description = "GitHub Actions action to install Task"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
codespell = "^2.2.2"
